### ISSUE TITLE
Runtime.ImportModuleError: Error: Cannot find module 'temp-units-conv'

### ISSUE THREAD

**Issue by jmkanagy** [blmille1/aws-sam-layers-template#3]
First of all, thank you for making this reference architecture. The layer usage documentation is severely lacking on AWS. 

Right now there seems to be an issue and I suspect that AWS has probably changed things.

When I run:
`$ sam local invoke Func2 --event events/event.json`

I get: 

2021-02-01T14:56:08.519Z        undefined       ERROR   Uncaught Exception      {"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'temp-units-conv'\nRequire stack:\n- /opt/nodejs/common.js\n- /var/task/func2Internal.js\n- /var/task/app.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","stack":["Runtime.ImportModuleError: Error: Cannot find module 'temp-units-conv'","Require stack:","- /opt/nodejs/common.js","- /var/task/func2Internal.js","- /var/task/app.js","- /var/runtime/UserFunction.js","- /var/runtime/index.js","    at _loadUserApp (/var/runtime/UserFunction.js: 100 :13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:43:30)","    at Module._compile (internal/modules/cjs/loader.js:999:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)","    at Module.load (internal/modules/cjs/loader.js:863:32)","    at Function.Module._load (internal/modules/cjs/loader.js:708:14)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)","    at internal/main/run_main_module.js:17:47"]}

My steps:
1. I downloaded/unpacked a .zip of your package, cd'ed into its root directory.
2. `$ sam build`
3. `$ sam deploy --guided`
4. `$ sam local invoke Func1 --event events/event.json` - works fine
5. `$ sam local invoke Func2 --event events/event.json` - gives the error above

**Comment by zcmgyu** [comment]
process.env.AWS is undefined

**Comment by BParvatkar** [comment]
Run `npm install` inside `layers/layer1/nodejs` folder to install the node packages from `package.json`.

**Comment by tonila** [comment]
I have the same issue. I tried to get this method working with my own project without success. I got similar error message. Finally found this error and downloaded this project and reproduced same error as OP. 

How to reproduce:
```
npm  i 
cd layers/layer1/nodejs
npm i
sam local invoke Func2 --event events/event.json
```

Result: 
```
Error: Cannot find module 'temp-units-conv'
```


**EDIT:** After debugging, I found out, that `node_modules` was not installed under `layers/layer1/nodejs`. I must have made a typo somewhere. Now I got it working. :)
